### ISSUE TITLE
Switch to Circle

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/x-dash#105]
Now that the battle with Circle 2.0 has been fought on our behalf we can switch from Travis. Travis is good but it has struggled with the install and build steps of this project - perhaps not too surprising as we've been using the free tier.

- [ ] add x-dash to service registry (as a component)
- [ ] add x-dash to vault (as a component)
- [ ] add custom circle config (for npm publish and docs site deployment)

**Comment by chee** [comment]
Prerequisites for this:
 * pride mode for Circle 2.0
 * comic sans mode for Circle 2.0

**Comment by quarterto** [comment]
travis specific stuff we're using and their circle/next equivalents:

| travis | circle |
|---|---|
| [secrets](https://github.com/Financial-Times/x-dash/blob/master/.travis.yml#L7) (dunno what these actually are lol) | vault |
| [npm publish](https://github.com/Financial-Times/x-dash/blob/master/.travis.yml#L25) | standard next component stuff/athloi scripts |
| [gh pages publish](https://github.com/Financial-Times/x-dash/blob/master/.travis.yml#L15) | 🤷‍♀️  |
| slack notifications | 🤷‍♀️  |

**Comment by i-like-robots** [comment]
For gh-pages I _think_ we can riff on the shell script folks commonly use (like this one: https://github.com/i-like-robots/grid-layout-demo/blob/master/deploy.sh)

Slack notifications 🤷‍♂️

**Comment by i-like-robots** [comment]
https://blog.frederikring.com/articles/deploying-github-pages-circle-ci/
