### ISSUE TITLE
Apps Getting Started guide broken link

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/x-dash#119]
The link to the 'Full Setup' guide under 'Slightly slower start' is broken in the generated docs: https://financial-times.github.io/x-dash/guides/apps/getting-started - I looked at the source Markdown file with the goal of opening a PR, but couldn't quite figure out what the path _should be_.

**Comment by i-like-robots** [comment]
Duplicate of #67

**Comment by simonplend** [comment]
Mah bad
