### ISSUE TITLE
document x-interaction serverside rendereing

### ISSUE THREAD

**Issue by quarterto** [Financial-Times/x-dash#128]

**Comment by i-like-robots** [comment]
Can I help with this?

**Comment by quarterto** [comment]
sure. i tried writing it a while ago and got stuck. main points to cover are:

- calling [`getInteractionSerialiser`](https://github.com/Financial-Times/x-dash/blob/master/components/x-interaction/src/concerns/serialiser.js) before rendering any components then calling the function it returns to output the data
- calling [`hydrate`](https://github.com/Financial-Times/x-dash/blob/master/components/x-interaction/src/Hydrate.jsx) on the clientside at `DOMContentLoaded` or some later event like a mousemove or touchmove to initialise components

the former package [`x-ssr-demo`](https://github.com/Financial-Times/x-dash/tree/6305eabfd94164b82f52a1b2208ab10116a81e1b/tools/x-ssr-demo) was an example of how to stitch these together, using `x-increment`
