### ISSUE TITLE
Teaser theme

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/x-dash#151]
Teasers may currently have one of four "themes":

- extra
- live
- opinion
- highlight

A package theme currently [takes precedence over other theme indicators][1].

The following teaser is for an article which is part of a package with the "extra" theme:

<img width="534" alt="screen shot 2018-09-04 at 09 15 01" src="https://user-images.githubusercontent.com/271645/45019023-2ec7f380-b023-11e8-8476-8461a0860199.png">

However not all themes apply to all teaser layouts. For instance the same content shown above loses all theming when using a small teaser layout:

<img width="540" alt="screen shot 2018-09-04 at 09 14 48" src="https://user-images.githubusercontent.com/271645/45019298-e2c97e80-b023-11e8-897a-b9ec55897393.png">

This may not be ideal because the content is tagged as an opinion piece and it may be expected that this content should fallback to the opinion theme.

The intention of grouping modifiers into groups ([see the spreadsheet here][2]) is to avoid situations where multiple conflicting modifiers can be applied leaving the CSS cascade to decide which to display. This led to unpredictable output, several annoying bugs, and has made the CSS code _very_ brittle.

A fix to this problem may be to _always_ append a "genre" indicator to the teaser and make this separate to the theme. Within o-teaser V3 we are already making some architectural changes to better separate layouts, themes and other modifiers so this could be another factor to consider in that work.

[1]: https://github.com/Financial-Times/x-dash/blob/master/components/x-teaser/src/Container.jsx#L13-L14
[2]: https://docs.google.com/spreadsheets/d/1HU_kTL5zzQhrIqIgAzCK6cHEXpJZgF0DBASP2jmaoYo/edit#gid=659053469

**Comment by i-like-robots** [comment]
Any ideas @chee and @adgad?

**Comment by adgad** [comment]
Wouldn't you still end up having specificity problems if separating genre and theme? For example, if you have a theme of extra and a genre of opinion - what decide the colour of the tag?

**Comment by i-like-robots** [comment]
Currently it can be a pain point because the order in which the styles are authored within o-teaser is not necessarily the order in which they are added to an apps stylesheet because the order can be specified by the implementer (see [this mixin here](https://github.com/Financial-Times/o-teaser/blob/master/src/scss/_teaser.scss#L7)).

If o-teaser was able to enforce the order its styles were applied then hopefully the cascade could be better used.

**Comment by chee** [comment]
would it be ungood to have a (possibly compiled-out at production build-time) validation step for props, with nice error messaging to say "you can't be small AND extra"?

**Comment by i-like-robots** [comment]
Which "theme" to apply is calculated from different data points rather than specified by the implementor:

- https://github.com/Financial-Times/x-dash/blob/master/components/x-teaser/src/Container.jsx#L13-L14
- https://github.com/Financial-Times/x-dash/blob/master/components/x-teaser/src/concerns/rules.js#L20-L31

Because I already had to refactor these rule functions (#144) I think it would be possible to consider the chosen layout without making too much spaghetti mess.

**Comment by i-like-robots** [comment]
According to n-display-metadata opinion metadata should take precedence over package metadata, so for consistency with that I am going to update the theme selection to be the same.

**Comment by i-like-robots** [comment]
Also to muddy the waters `/opinion` is opinion the section not the genre so not everything should be blue! 😉

**Comment by i-like-robots** [comment]
With uncanny timing this is on the front page right now!

<img width="248" alt="screen shot 2018-09-04 at 14 28 04" src="https://user-images.githubusercontent.com/271645/45034233-c989f780-b04e-11e8-9307-fc2d3f40a0e3.png">
