### ISSUE TITLE
external actions in x-interaction

### ISSUE THREAD

**Issue by quarterto** [Financial-Times/x-dash#163]
## the problem

it would be useful for certain components to be able to expose actions that can be called from other parts of an app consuming the component. some use cases for this:

- triggering loading data on page load, or component visibility
- showing a component when an event is triggered on a non-x-dash component, e.g. a dialog or menu

there's currently no way to access the actions from an x-interaction wrapped component outside of the component, and this is the only way to alter a component once rendered.

## concerns

there's a few things we need to be careful of, which are mostly things the App is concerned with, as a long-lived web page:

- event listeners must be cleaned up properly when a component is unmounted
- any external actions must be triggered on the right instance, in case multiple instances of one component are rendered at the same time
- needs to work cross-runtime; there might be some nuances in how react & preact handle `ref`s that could cause problems, but idk
- needs to work with `x-interaction` server-side rendering, where the code rendering the component isn't under the app's control, so they don't have access to the instance

## proposals

for a component that uses `x-interaction`, such as `x-increment`:

```jsx
const withIncrementActions = withActions(() => ({
	increment(event) {
		return ({count}) => ({
			count: count + event.detail.amount || 1
		});
	},
}));

const BaseIncrement = ({count, actions: {increment}}) => <div>
	{count}
	<button onClick={increment}>Increment</button>
</div>;

const Increment = withIncrementActions(BaseIncrement);
```

here's a couple of ideas for APIs for triggering these actions externally (these ideas aren't alternatives, they're complementary):

### `actionRef`

allow an app that's rendering it directly to access actions using `actionRef`:

```jsx
import {Increment} from '@financial-times/x-increment';
import React, {Component} from 'react';

class Foo extends Component {
	doAThing() {
		if(this.incrementActions) {
			this.incrementActions.increment({detail: {amount: 5}});
		}
	}

	render() {
		return <Increment actionRef={actions => this.incrementActions = actions} />;
	}
}
```

| pros | cons |
|-|-|
| scoped to the rendering of the parent component | restricted to within other components |
| can pass in any args | possible cross-runtime incompatibility? |

### `CustomEvent`

allow an app rendering via x-interaction SSR to trigger a custom event on a DOM element which fires the action:

#### server-side

```handlebars
{{{x package="x-increment" component="Increment" id="x-increment-1"}}}
```

#### client-side

```js
import {hydrate} from '@financial-times/x-interaction';

document.addEventListener('DOMContentLoaded', hydrate);

function doAThing() {
	const el = document.querySelector('[data-x-dash-id="x-increment-1"]');
	const event = new CustomEvent('x-interaction.increment', {
		detail: {amount: 5}
	});
	el.dispatchEvent(event);
}
```

| pros | cons |
|-|-|
| allows passing in args (that can be structurally cloned) as the event detail | requires predictable ids |
| scoped to instance because DOM node | referring to action by string name may be unpredictable |

---

what do people think of these proposals? do they fit your use case? do you have any alternative suggestions?

**Comment by benbarnett** [comment]
Sounds good! I think the `CustomEvent` approach would work well for x-gift-article's needs. 

So this would shift the responsibility of loading/unloading event listeners into x-interaction? (or something core to x-dash?)

**Comment by quarterto** [comment]
it'd be in x-interaction (or some other component it would depend on)

**Comment by dan-searle** [comment]
Ah, right I see. How would the app code that wants to trigger an action on the x-dash component, know the component's `x-dash-id`?

**Comment by quarterto** [comment]
when rendering an `x-interaction` component you can specify an `id` (if you don't you get a randomly-generated one). consumers would have to specify a unique static id per instance of a component

**Comment by dan-searle** [comment]
Thinking about this some more, predictable IDs might not be necessary in many cases, as other attributes might be sufficient for selection purposes. E.g., setting `ArticleSaveButton` states:

```es6
document.querySelectorAll('.article-save-button[data-content-id="saved-content-uuid"]').forEach(el => {
  const event = new CustomEvent('x-interaction.article-share-button', {
    detail: { saved: true }
  });
  el.dispatchEvent(event);
});
```

**Comment by quarterto** [comment]
it's up to the app how to select the element to trigger the event on; i used `data-x-dash-id` because it's already a thing in `x-interaction` server side rendering. good point about the event name, we don't need the component name. i think i'll keep action name in the event name, that way `detail` is just for arguments for the action.

**Comment by quarterto** [comment]
on second thoughts, using a single event means we only need one listener, and don't need to inspect the action names

**Comment by quarterto** [comment]
for that kind of use case, how i'd see it working is replacing the component's actions before rendering (i.e. rewrapping with `withActions`)

**Comment by dan-searle** [comment]
ah! 💡

**Comment by quarterto** [comment]
looks about right, and the App would do its own `withActions`, it's just clientside rendered

**Comment by dan-searle** [comment]
Actually, this won't help for this use case. **x-article-save-button** won't be used directly by the web or the app, instead a new timeline feed component will be used (which itself will be composed of **x-teaser**s and **x-article-save-button**s).

**Comment by quarterto** [comment]
as with `x-teaser`, which lets you [override the `Link` subcomponent](https://github.com/Financial-Times/x-dash/blob/612a852/components/x-teaser/src/Link.jsx), could the article feed let you specify your own `ArticleSaveButton`? which in the App could just be the re-wrapped `x-article-save-button`
