### ISSUE TITLE
Update snapshots incorrectly documented

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/x-dash#167]
The [docs](https://financial-times.github.io/x-dash/guides/components/setup#updating-snapshots) say to regenerate snapshots, run `npm test -- --updateSnapshot`, but that isn't working.

The following work:
* `npm test -- -- --updateSnapshot` (an additional `--`)
* `npm run jest -- --updateSnapshot`

Might be worth adding a new command in the `makefile`?

**Comment by quarterto** [comment]
ah, good spot. a makefile command would be good

**Comment by dan-searle** [comment]
ok cool, I'll raise a PR
