### ISSUE TITLE
investigate generating sketch files for components

### ISSUE THREAD

**Issue by quarterto** [Financial-Times/x-dash#186]
using something like [react-sketchapp](https://github.com/airbnb/react-sketchapp)

**Comment by quarterto** [comment]
looks like react-sketchapp doesn't support actual CSS which would make using origami styles a little uh not possible

**Comment by i-like-robots** [comment]
This is something a few folks have asked but I'm not sure if it's possible with our current setup - technically or logically - because there is no one source of truth for component styles.

**Comment by i-like-robots** [comment]
I'm going to close this issue for now as I don't see any means to make this possible in any useful way. Should that change we can reopen the issue to continue discussions.
