### ISSUE TITLE
x-interaction wrapped components' action functions, always receive initial props?

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/x-dash#224]
...rather than current props?

I'm seeing this with both [x-follow-button](https://github.com/Financial-Times/x-dash/blob/follow-button/components/x-follow-button/src/FollowButton.jsx#L8) and [article-save-button](https://github.com/Financial-Times/x-dash/blob/x-article-save-button/components/x-article-save-button/src/ArticleSaveButton.jsx#L8).

When the component props change - e.g. the **x-follow-button** `isSelected` prop changes from `true` to `false`, the action function's `currentProps` are still the props initial props when it was first constructed (`isSelected === true`).

```es6
const followButtonActions = withActions(initialProps => ({
	triggerFollowUnfollow(rootElement) {
		return currentProps => {
                   // currentProps always seems to be the same as initialProps?
			const detail = {
				action: currentProps.isSelected ? 'remove' : 'add',
```

Is this a fault with the components' implementation, or a bug with x-interaction? I think this was working a week or so ago.

**Comment by quarterto** [comment]
unless i'm missing something, i don't see anywhere in either of those components that `actions.followed`/`actions.saved` is called? i.e. nothing's ever updating the state?

**Comment by dan-searle** [comment]
The component is being re-rendered by its parent, with the updated props: http://git.svc.ft.com/projects/FTA/repos/ft-app/pull-requests/3869/diff#lib/javascript/myft/v2/manage.js

**Comment by quarterto** [comment]
okay. in this case, because the action doesn't change state directly (and the actions that have state changes aren't used) i would recommend not using `x-interaction` for these components. it's hard to orchestrate state changes from within and props changes from outside. it _should_ work but i don't know why it isn't in this case.

**Comment by dan-searle** [comment]
OK, sure. This was our original approach, but we've now moved mostly towards just re-rendering with changed props, so I think we'll stop using `x-interaction` for the save and follow buttons and focus our efforts on consistently using that approach.

**Comment by dan-searle** [comment]
We're running into this problem in ft-app too, as the the whole page is a Preact tree and so the `x-interaction`-wrapper of `x-topic-search` gets re-invoked whenever topics change - effectively reseting its state.

**Comment by quarterto** [comment]
i've added a test for this in #251. i thought we had a test already but it was only testing rendering, not state updaters.
