### ISSUE TITLE
x-dash test fails when component is a class

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/x-dash#240]
When we extend Preact's `Component` component class instead of using `x-interaction` for components that have state, and run `npm run jest`, we get this error:

```console
  ● @financial-times/x-topic-search › renders a default Topic Search Bar x-topic-search

    TypeError: Cannot call a class as a function
```

**Comment by benbarnett** [comment]
To publicise our discussion on Slack just now:

Looks like https://github.com/Financial-Times/x-dash/blob/x-topic-search-as-class/__tests__/snapshots.test.js#L28 is forcing a functional style component render. Switching over to `renderer.create(<component {...props} />)` should make this more agnostic.

This requires x-engine though?
