### ISSUE TITLE
Docs section of the x-dash site is broken

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/x-dash#357]
**Expected behaviour**

When I navigate to the [x-dash website](https://financial-times.github.io/x-dash/) I am able to browse to and view the various pages under the 'Docs' section.

**Actual behaviour**

You will receive 404 errors of varying sorts and be unable to browse the 'Docs' section.

**Steps to reproduce**

_Scenario A_

1. Navigate in your browser to the [x-dash website](https://financial-times.github.io/x-dash/)
2. Click on the top nav `Docs` link or the `Get started` button
3. You will see the following error in your browser's console: `Uncaught (in promise) Error: 404 page could not be found. Checkout https://www.gatsbyjs.org/docs/add-404-page/`

_Scenario B_

1. Navigate in your browser to the [x-dash repository on GitHub](https://github.com/Financial-Times/x-dash#readme)
2. Click on the `getting started` link in the `README`
3. You will receive a GitHub Pages 404 error page

**Comment by i-like-robots** [comment]
This is very odd... it appears the pages are being rendered into subfolders.

When running Gatsby locally these pages are being created in a folder called `x-dash`.

When running the production build they are being put in a folder called `build`:
https://github.com/Financial-Times/x-dash/tree/gh-pages/build/docs
