### ISSUE TITLE
Monorepo management tooling

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/x-dash#90]
So far we have been using Lerna to manage the installation and publishing of the multiple packages in this repo. We chose Lerna because it is the de-facto monorepo management tool available for Node and it is used by many very popular projects.

However, so far we have been disappointed and oftentimes frustrated by it. It is relatively slow and when it breaks - which it does too often to give us confidence - it usually does so silently. This has been a common sight:

<img width="832" alt="screen shot 2018-07-19 at 15 47 13" src="https://user-images.githubusercontent.com/271645/42950046-170f2916-8b6b-11e8-9d82-6dc4ae447745.png">

The problems can be very hard to debug because Lerna has an extremely complicated architecture. It is not a project we can easily dig into and help to support. For these reasons we have investigated the alternatives, including:

- https://www.npmjs.com/package/@microsoft/rush
- https://www.npmjs.com/package/oao
- http://boltpkg.com/

All 3 are solid projects and differ little in configuration and usage. But, they all use Yarn and/or hoisting to minimise the size and number of packages installed. This is a good idea on paper but in practice it causes havoc because Node's module resolution algorithm depends so much on context, and that context is lost when not managing packages on an individual basis.

All of the tools discussed above include deep integration with Git with many checks and balances to ensure releases are valid, change logs are updated etc. We release on CI so these complicated features are of no use to us at this time.

As far as I can tell there are 3 jobs that a monorepo management tool needs to do for us:

- Install external dependencies and cross-link local packages
- Publish all packages in lock-step
- Run a given script in the context of every package

A script can be run in the context of each package with a few lines of bash, for example to run `npm install`:

```sh
targets=$(find {components,packages,tools}/x-*/package.json)

for $item in $targets; do
    target=$(dirname $item)
    (cd $target && exec npm install)
done
```

However because packages may depend on each other several types of task must be performed _in order_. This means finding the cross linked dependencies and sorting them. This is [not too hard](https://gist.github.com/i-like-robots/79cc1c647a941dbdeeebd28e2806f8a1) but it is important to see problems through this lens.

Some monorepo projects are managed using a set of custom scripts. This is transparent but we have always had issues maintaining homebrew tooling in Next and people tend to feel especially burnt when it fails and they have to spend time yak shaving. For this reason if we do decide to roll-our-own then it would be sensible to keep it to the absolute minimum. Some examples of this approach include:

- [cycle.js](https://github.com/cyclejs/cyclejs/tree/master/.scripts)
- [React](https://github.com/facebook/react/tree/master/scripts)

Thoughts?

**Comment by quarterto** [comment]
agree on all of this. athloi was originally written just to be the nice interface, and i only added the script running stuff out of frustration at lerna; it's gotten a bit bloated. i am v keen to keep the discoverability of it though.

**Comment by i-like-robots** [comment]
OK so, we need to:

- A tool able to run a given command in the context of each package in order 
- Update cross dependencies to use relative `:file:` paths so NPM can symlink them
- Add a custom release script to rewrite these dependencies before publishing with the given version number
- Gather common tasks into the `makefile` 
- Update quick start docs

**Comment by wheresrhys** [comment]
> we have always had issues maintaining homebrew tooling in Next

It'd be good to expand on this. Divide and conquer to see if we can improve on them. e.g I can think of a few *(with some stub solutions)*
- written in Make, which few are familiar with 
*keep use of make to a minimum. Write mostly in JS*
- written by 1 person 
*have some shared ownership and governance... x-dash already seems like a massive improvement on past failures*
-...

**Comment by i-like-robots** [comment]
I think I can sum it my thoughts on that note in 3 related points:

1. They're often esoteric (as you mention). I think tooling targeted for use by the wider team should ideally involve as many of those who are meant to use it as possible and defining clear goals.
2. Tools often sprawl in responsibility. I think feature creep is a symptom of the point above and too much short term thinking, _"I'll just hack this on here for now..."_
3. Both of the above are promote a lack of responsibility and ownership of code which in turn means features miss out on thorough review (or even [radical candor][2]) and the "temporary" hacks don't cleaned up.

Hopefully by [applying better governance][1] within x-dash will help to mitigate these problems.  into more long-term thinking, putting items in a roadmap, saying "no" more often.

[1]: https://github.com/Financial-Times/x-dash/blob/894711955bdf4ac399c5aa5af1e31fb9ec19e342/contribution.md#opening-a-pull-request
[2]: https://www.ianfeather.co.uk/radical-candor-in-code-review/
